[run]
  timeout = "10m"
  skip-files = []

[linters-settings]

  [linters-settings.govet]
    check-shadowing = false

  [linters-settings.golint]
    min-confidence = 0.0

  [linters-settings.gocyclo]
    min-complexity = 14.0

  [linters-settings.maligned]
    suggest-new = true

  [linters-settings.goconst]
    min-len = 3.0
    min-occurrences = 4.0

  [linters-settings.misspell]
    locale = "US"

  [linters-settings.funlen]
    lines = 230
    statements = 120

[linters]
  enable-all = true
  disable = [
    "gocyclo",
    "gosec",
    "dupl",
    "maligned",
    "lll",
    "unparam",
    "prealloc",
    "scopelint",
    "gochecknoinits",
    "gochecknoglobals",
    "godox",
    "gocognit",
    "bodyclose",
    "wsl",
    "gomnd",
    "stylecheck",
  ]
