project_name: enve

dist: bin

env:
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org,https://gocenter.io,direct

builds:
  - binary: enve
    main: main.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/joseluisq/enve/cmd.versionNumber={{.Version}} -X github.com/joseluisq/enve/cmd.buildTime={{.Date}}
    goos:
      - linux
      - darwin
      - freebsd
      - openbsd
    goarch:
      - amd64
      - arm
      - arm64
      - ppc64le
    goarm:
      - 7
      - 6
      - 5
    ignore:
      - goos: darwin
      - goos: openbsd
        goarch: arm
      - goos: openbsd
        goarch: arm64
      - goos: freebsd
        goarch: arm64

archives:
  - id: enve
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: tar.gz
    replacements:
      darwin: darwin
      linux: linux
      amd64: x86_64
    files:
      - LICENSE-APACHE
      - LICENSE-MIT

release:
  prerelease: auto
changelog:
  skip: true

signs:
  -
    cmd: gpg
    args:
      - --output
      - $signature
      - --detach-sig
      - $artifact
    signature: ${artifact}.sig
    artifacts: none

snapshot:
  name_template: "{{ .Version }}"

checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_checksums.txt"
