version: 2

project_name: enve

dist: bin

env:
  - GO111MODULE=on

builds:
  - binary: enve
    main: main.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/joseluisq/enve/cmd.versionNumber={{.Version}} -X github.com/joseluisq/enve/cmd.buildCommit={{.Commit}} -X github.com/joseluisq/enve/cmd.buildTime={{.Date}}
    goos:
      - linux
      - darwin
      - windows
      - freebsd
      - openbsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
      - ppc64le
    goarm:
      - 7
      - 6
      - 5
    ignore:
      - goos: darwin
        goarch: 386
      - goos: openbsd
        goarch: arm
      - goos: openbsd
        goarch: arm64
      - goos: freebsd
        goarch: arm64

archives:
  - id: enve
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: tar.gz
    files:
      - LICENSE-APACHE
      - LICENSE-MIT

release:
  prerelease: auto

checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_checksums.txt"
